url: "http://rennes.afup.org"

title: "AFUP Rennes"
description: >-
  Antenne AFUP Rennes
twitter_username: AFUP_Rennes
meetup_url: "https://www.meetup.com/fr-FR/AFUP-Rennes/"

permalink: /posts/:title

ga_ua: "G-BHKX3BDVTB"
home_featured_articles_count: 2

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Makefile
   - docker-compose.yml
   - docker-compose.override.yml-dist
   - docker-compose.override.yml
   - Gemfile
   - Gemfile.lock

feed:
  path: feed

